### ISSUE TITLE
bad input crashes R

### ISSUE THREAD

**Issue by erikriverson** [glycerine/rmq#2]
Hello, was very happy to find this project after searching for working with msgpack in R! I'm processing a bunch of msgpack'd data, some of which I only have partial messages for, and therefore is not deserializable. The solution may be "don't do that", but thought I would report. 

Here is one of those 'partial' messages: 

```
library(rmq)

crash <- as.raw(c(0x9a, 0xad, 0xe6, 0x57, 0xb8, 0x4e, 0xa1, 0x79, 0xcb, 
0x40, 0x75, 0xb4, 0x48, 0xe8, 0xa7, 0x1d, 0xe7, 0xa1, 0x7a, 0xcb, 
0x3f, 0xeb, 0x32, 0xa6, 0x0f, 0xc9, 0xa1, 0x9f, 0xa2, 0x54, 0x73, 
0xcf, 0x00, 0x00, 0x01, 0x57, 0x4e, 0x1a, 0xbb, 0x5c, 0xa3, 0x53, 
0x74, 0x73, 0xce, 0x00, 0x02, 0x38, 0x6c, 0xa3, 0x43, 0x74, 0x73, 
0xce, 0x00, 0x01, 0x54, 0x88, 0xa2, 0x54, 0x7a, 0xb1, 0x41, 0x6d, 
0x65, 0x72, 0x69, 0x63, 0x61, 0x2f, 0x41, 0x6e, 0x63, 0x68, 0x6f, 
0x72, 0x61, 0x67, 0x65, 0xa6, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 
0xb8, 0x73, 0x61, 0x6d, 0x73, 0x75, 0x6e, 0x67, 0x20, 0x53, 0x41, 
0x4d, 0x53, 0x55, 0x4e, 0x47, 0x2d, 0x53, 0x4d, 0x2d, 0x47, 0x39, 
0x33, 0x30, 0x41, 0xa6, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0xb0, 
0x64, 0x35, 0x39, 0x64, 0x34, 0x33, 0x33, 0x30, 0x33, 0x37, 0x33, 
0x37, 0x63, 0x36, 0x37, 0x35))
from.msgpack(crash)
```

```
Process R:2 exited abnormally with code 2 at Tue Oct 25 14:30:35 2016
panic: interface conversion: interface is int64, not string

goroutine 17 [running, locked to thread]:
panic(0x1088c59a0, 0xc82013a6c0)
    /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
main.decodeHelper(0x1087be460, 0xc82013e640, 0x0, 0x1, 0x0)
    /Users/erik/src/github.com/glycerine/rmq/src/rmq/rmq.go:578 +0x274a
main.decodeMsgpackToR(0xc82017e000, 0x87, 0x87, 0xc82017e000)
    /Users/erik/src/github.com/glycerine/rmq/src/rmq/rmq.go:503 +0x367
main.FromMsgpack(0x7f853a516100, 0x108ae1238)
    /Users/erik/src/github.com/glycerine/rmq/src/rmq/rmq.go:753 +0x374
main._cgoexpwrap_fc3f51395541_FromMsgpack(0x7f853a516100, 0x0)
    rmq/_obj/_cgo_gotypes.go:721 +0x5a

```

**Comment by glycerine** [comment]
Hi @erikriverson --  Interesting! Thanks for letting me know about it.

I'm certainly concerned that bad input causes rmq to crash the whole R process.

I pushed just now a commit, 95fd97778df1b31f91e6b37c4024468b0a935b85 , which catches the panic and returns control to R instead of crashing the process.

What is more interesting is that your msgpack message, crash, appears to start with an array that contains different types.... with Verbose = true in vprint.go, we see:

```
>  from.msgpack(crash) 
2016-10-29 13:17:05.814 -0500 CDT decoded type : []interface {}
2016-10-29 13:17:05.814 -0500 CDT decoded value: []interface {}{"\xe6W\xb8N\xa1y\xcb@u\xb4H\xe8\xa7", 29, -25, "z", 0.8499327, "Ts", 1474484157276, "Sts", 145516, "Cts"}
2016-10-29 13:17:05.814 -0500 CDT decodeHelper() at depth 0, decoded type is []interface {}
2016-10-29 13:17:05.814 -0500 CDT depth 0 found []interface{} case: val = []interface {}{"\xe6W\xb8N\xa1y\xcb@u\xb4H\xe8\xa7", 29, -25, "z", 0.8499327, "Ts", 1474484157276, "Sts", 145516, "Cts"}
2016-10-29 13:17:05.814 -0500 CDT  ... also at depth 0,   ---> first has type 'string' and value '\346W\270N\241y\313@u\264H\350\247'
Error in from.msgpack(crash) :
  rmq.decodeHelper detected malformed msgpack panic: interface conversion: interface is int64, not string
goroutine 17 [running, locked to thread]:
runtime/debug.Stack(0xc420075c00, 0xc420075c40, 0x34)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
main.decodeHelper.func1()
        /Users/jaten/go/src/github.com/glycerine/rmq/src/rmq/rmq.go:534 +0xfc
panic(0x111dc9180, 0xc420075c00)
        /usr/local/go/src/runtime/panic.go:458 +0x243
main.decodeHelper(0x111d96800, 0xc4200df8a0, 0x0, 0x1, 0x0)
        /Users/jaten/go/src/github.com/glycerine/rmq/src/rmq/rmq.go:593 +0x1936
main.decodeMsgpackToR(0xc42008c630, 0x87, 0x87, 0xc42008c630)
        /Users/jaten/go/src/github.com/glycerine/rmq/src/rmq/rmq.go:504 +0x1de
main.FromMsgpack(0x7ffa2b70f550, 0x111eada80)
        /Users/jaten/go/src/github.com/glycerine/rmq/src/rmq/rmq.go:768 +0x2d0
main._cgoexpwrap_711ce02f3b98_FromMsgpack(0x7ffa2b70f550, 0x0)
        rmq/_obj/_cgo_gotypes.go:759 +0x5a
> 
```

Lists can hold varying types is R, and they are allowed to do that in msgpack, but it's rarely a good idea. I'm hesitant to support it. (You almost always want a map in this case.) In fact, it looks rather like a message got truncated and then a second message that had a map (from strings to numbers) in it got tacked onto the end.

**Comment by glycerine** [comment]
I'm going to close this out as fixed, but please open a new issue if you have any problems after trying the fix; or if you have additional ideas for improvement.
